### ISSUE TITLE
能力者设定

### ISSUE THREAD

**Issue by FrankHB** [lazyparser/weloveinterns#104]
how-do-we-rank-interns.md 有一些设定上的问题……

[常盘台中学](http://toaru.huijiwiki.com/wiki/常盘台中学)只收女生；原则上要求至少大能力者（技术交换生有例外）。好吧，这个先不提……

* 评价能力者强度的[身体检查(System Scan)](http://toaru.huijiwiki.com/wiki/身体检查)不是常盘台中学独有的项目。
* 强度是[超能力开发计划(Power Curriculum Program)](http://toaru.huijiwiki.com/wiki/超能力开发计划) 定义的。
* 身体检查是超能力开发计划的一部分，原则上至少要有劳务合同。

顺便，能力者强度上限由机密的[素养判定(Parameter List)](http://toaru.huijiwiki.com/wiki/素养判定)测试，这个要重现嘛？

**Comment by lazyparser** [comment]
> how-do-we-rank-interns.md 有一些设定上的问题……
> 
> [常盘台中学](http://toaru.huijiwiki.com/wiki/%E5%B8%B8%E7%9B%98%E5%8F%B0%E4%B8%AD%E5%AD%A6)只收女生；原则上要求至少大能力者（技术交换生有例外）。好吧，这个先不提……

我们（我）确实是很想招收女生来着……但是不知道为什么，只有男性学生投递简历。。。

> 
>     * 评价能力者强度的[身体检查(System Scan)](http://toaru.huijiwiki.com/wiki/%E8%BA%AB%E4%BD%93%E6%A3%80%E6%9F%A5)不是常盘台中学独有的项目。

我们不检查身体，直接翻看脑子的能力（这里neta了实力至上主义的教室233）


> 
>     * 强度是[超能力开发计划(Power Curriculum Program)](http://toaru.huijiwiki.com/wiki/%E8%B6%85%E8%83%BD%E5%8A%9B%E5%BC%80%E5%8F%91%E8%AE%A1%E5%88%92) 定义的。
> 
>     * 身体检查是超能力开发计划的一部分，原则上至少要有劳务合同。

劳动合同我们有的（真）

> 
> 
> 顺便，能力者强度上限由机密的[素养判定(Parameter List)](http://toaru.huijiwiki.com/wiki/%E7%B4%A0%E5%85%BB%E5%88%A4%E5%AE%9A)测试，这个要重现嘛？

进入 P · L · C · T 会有三次试炼（不是re0那么恐怖的）结果也是机密的（

**Comment by ice1000** [comment]
说是常盘台其实是因为我们比较小，大点应该就直接叫学园都市了。

**Comment by lazyparser** [comment]
> 说是常盘台其实是因为我们比较小，大点应该就直接叫学园都市了。

我直呼好家伙

**Comment by FrankHB** [comment]
> 说是常盘台其实是因为我们比较小，大点应该就直接叫学园都市了。

收不收原石能力者（

**Comment by ice1000** [comment]
> > 说是常盘台其实是因为我们比较小，大点应该就直接叫学园都市了。
> 
> 收不收原石能力者（

这要看原石能力者在现实投影的目标是什么样的技术了，对口的话我觉得就会收。比如如果你说这是对应范畴论的话，那我不就可以算一个 ((((((

**Comment by FrankHB** [comment]
> 
> 这要看原石能力者在现实投影的目标是什么样的技术了，对口的话我觉得就会收。比如如果你说这是对应范畴论的话，那我不就可以算一个 ((((((

说起来按设定常盘台应该也不挑能力者类型的吧，只是卡等级……

（……业界应该是有不少 )))))) 能力者。）

**Comment by lazyparser** [comment]
含泪关闭2020年旧贴（Thanks)

**Comment by ice1000** [comment]
完结撒花
