### ISSUE TITLE
是否可以将 PLCT 理解为一个公益性质的公司？

### ISSUE THREAD

**Issue by ice1000** [lazyparser/weloveinterns#109]
PLCT 的业务似乎没有直接的商业利益 :thinking:

**Comment by lazyparser** [comment]
非常的类似了。PLCT Lab 目前并不是一个法律意义上的实体，是作为 中国科学院软件研究所 智能软件研究中心 下属的一个 工程团队存在的。公司化运作，能够自负盈亏。不赚钱。

**Comment by ice1000** [comment]
🥺

**Comment by ytfh44** [comment]
> 
> 
> PLCT 的业务似乎没有直接的商业利益 🤔

像北京谋智那样？

**Comment by lazyparser** [comment]
> > PLCT 的业务似乎没有直接的商业利益 🤔
> 
> 像北京谋智那样？

第一次听说。
Mozilla？那么类似。很多管理方法抄自Mozilla
