### ISSUE TITLE
[goodfirstbug]进度报告页面丢失

### ISSUE THREAD

**Issue by sunnyorcloudy** [lazyparser/weloveinterns#28]
需要在进度报告页面创建对应内容。
现在的状态是404错误。
https://github.com/lazyparser/weloveinterns/blob/master/reports.md

**Comment by lazyparser** [comment]
nice catch :)

是之前柯银练习提交的时候（commit-id a9fa6661e6aabbffd591897fc9e1937d9474d35b ）误删了。

提交一个PR，重新创建一个 reports.md 并在里面加入指向现有 reports/ 目录下的md文件链接。

**Comment by lazyparser** [comment]
fixed by pull29
