### ISSUE TITLE
修复ros-checklist.md中的图片URL

### ISSUE THREAD

**Issue by sunnyorcloudy** [lazyparser/weloveinterns#72]
看上去是小海龟图片对应的名称大小写的问题，让图片无法正常显示。

现在使用的图片地址：
https://github.com/lazyparser/weloveinterns/blob/master/images/ROS/turtle.png

根据仓库里面存储的图片情况，图片名称应为：Turtle.png

**Comment by lazyparser** [comment]
Fixed by pull request #73
