### ISSUE TITLE
为什么git把report拆成了一个大写和一个小写

### ISSUE THREAD

**Issue by nephashi** [lazyparser/weloveinterns#92]
我push的时候本地明明是同一个目录。而且我本地和远程都只有1个分支。

**Comment by lazyparser** [comment]
实际上是之前重构过一次，全部改成小写了。我看看是不是合并的问题

**Comment by lazyparser** [comment]
hi @nephashi 你是在什么os上发现的？

**Comment by nephashi** [comment]
是在windows上发现的

**Comment by lazyparser** [comment]
是这样子的我们的仓库已经完全改成了小写的目录了，可能是windows不大小写导致的；
直接改变一个文件（目录）的大小写可能没有效果，技巧是先改成别的名字然后改回来正确的大小写。
